name: Release Schema

on:
    push:
        tags:
            - 'v*.*.*' # Matches tags like v1.0.0, v1.1.2

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ github.ref_name }}
                  name: Ottolog Schema ${{ github.ref_name }}
                  body_path: CHANGELOG.md
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
